### ISSUE TITLE
Observer spawns in Space Dimensions Mod worlds

### ISSUE THREAD

**Issue by Niketats** [CartoonishVillain/Observed#1]
a lot of Observers spawns in Space Dimensions Mod worlds, and so, dying without oxygen

**Comment by CartoonishVillain** [comment]
Fortunately, I have just reworked the spawn system. This **should** be a quick and easy fix. Version 1.2.4.1 for 1.18.2 will resolve this. Will close this issue when the build is uploaded, though it may take some time to propagate (for CF to allow you to download it)

**Comment by CartoonishVillain** [comment]
Update uploaded. Reviewing processes and server synchronization pending. Could be a matter of minutes, could be days. Depends on how they are feeling.

Thank you for reporting!

**Comment by Niketats** [comment]
thx
